- Source/LightboxTransition.swift
> Added some animations

- Demos/LightboxDemo/LightboxDemo/Info.plist
- Demos/LightboxDemo/LightboxDemo/MainViewController.swift
- Demos/LightboxDemo/Podfile.lock
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxDataSource.swift
- Source/LightboxTransition.swift
- Source/LightboxView.swift
- Source/LightboxViewCell.swift
Crashes at runtime because of AutoLayout.
Working on this.
Here I've commented out the code that causes the crash. In progress.
> [WIP]Update from master / Update syntax for Swift 2.0

- Demos/LightboxDemo/LightboxDemo.xcodeproj/project.pbxproj
- Source/LightboxTransition.swift
Demo:
https://youtu.be/8eL8xfU06Rg
I've made starting alpha value to be very low to avoid blinking.
> Fix blinking

- Source/LightboxController.swift
> Spacing between pages

- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/PageView.swift
@zenangst @RamonGilabert 
1) Implement zoom in / zoom out on double tap.
2) Hide controls on zoom in.
3) Fix a bug with invalid image view size on zoom in.
> Zoom on double tap

- Source/Library/LightboxTransition.swift
- Source/Library/UIView+Gradient.swift
- Source/LightboxController.swift
- Source/Views/InfoLabel.swift
@zenangst @RamonGilabert Minor fixes according to comments from https://github.com/hyperoslo/Lightbox/pull/52
> Minor fixes

- Demos/DemoLightbox/DemoLightbox/ViewController.swift
- Source/LightboxController.swift
This PR adds an optional dynamic background feature that can be enabled by setting `dynamicBackground` to `true` on `LightboxController`.
It looks like this:
> Feature dynamic background

- .travis.yml
- Source/LightboxImage.swift
This PR makes the properties on `LightboxImage` public.
> Refactor Lightbox image

- Source/LightboxController.swift
@zenangst @RamonGilabert So we could set images not only in the `init`.
> Feature: set images

- Source/LightboxImage.swift
@RamonGilabert @zenangst :smile:
> Lightbox image is a struct now

- Demos/DemoLightbox/Podfile.lock
- Source/LightboxController.swift
- Source/LightboxImage.swift
@zenangst @RamonGilabert Apparently it's a fix.
> Fix a crash with configure pages in the init

- Demos/DemoLightbox/DemoLightbox/ViewController.swift
- Source/Library/LightboxTransition.swift
- Source/LightboxController.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
- Source/Views/PageView.swift
- Use #selector
- Use -=1
- Use ..< range operator
> Update to Swift 2.2 syntax

- Source/LightboxController.swift
So that user is not surprised 😄
> Add animation when changing alpha

- Source/LightboxController.swift
- Take `spacing` into account
- Handle when the last item is deleted
After
> Adjust to make removal anomation more smooth

- .swiftlint.yml
- Demos/DemoLightbox/.swiftlint.yml
- Demos/DemoLightbox/DemoLightbox.xcodeproj/project.pbxproj
- Demos/DemoLightbox/Podfile
- Demos/DemoLightbox/Podfile.lock
- Source/Library/LightboxTransition.swift
- Source/LightboxController.swift
- Source/Views/FooterView.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
- Source/Views/PageView.swift
With the help of the Magician aka @RamonGilabert, we solved a huge memory leak that was caused by a strong reference to the lightbox controller.
This PR also introduces and fixes som swift lint warnings.
> Fix strong reference

- Demos/DemoLightbox/DemoLightbox/Info.plist
- Source/LightboxImage.swift
- Source/Views/LoadingIndicator.swift
- Source/Views/PageView.swift
It should be nice if there is an indicator showing what's going on
> Add loading indicator

- Source/Library/LightboxTransition.swift
Hi there Hyper Team 👋 
I opened an issue this morning and fixed it by myself.
This fixes #102.
Have a nice day,
Roman
> Fix half-black screen after dismissal

- Source/LightboxConfig.swift
- Source/Views/PageView.swift
- This adds `makeLoadingIndicator` to config to make it customisable
> Allow loadingIndicator to be configured

- README.md
- Source/LightboxConfig.swift
- Source/LightboxImage.swift
- Fix https://github.com/hyperoslo/Lightbox/issues/148 by exposing `loadImage`. Defaults to Imaginary
- Update README
> Allow custom download

- Lightbox.xcodeproj/project.pbxproj
remove copy framework build phase which should make only on app building and not framework (nested framework aren't allowed by Apple)
> Carthage compatibility

- Example/DemoLightbox/DemoLightbox.xcodeproj/project.pbxproj
- Example/DemoLightbox/Podfile.lock
- Source/LightboxController.swift
- Set origin properly
- This fixes https://github.com/hyperoslo/Lightbox/issues/166
> Fix footer frame

- Source/LightboxImage.swift
I was in need for a custom closure to provide images generated from Data on the background thread. Maybe it will be helpful to other ppl, since custom data provider is always useful.
> Added support to init with closure

- Source/LightboxController.swift
- iOSDemo/ViewController.swift
Fixes https://github.com/hyperoslo/Lightbox/issues/245
> Force modal presentation style

- Source/LightboxController.swift
Fix app crash when tap delete button.
> Fix app crash when tap delete button.

- Source/LightboxController.swift
Added LightboxControllerDeleteDelegate to have a delegate for image deleting action
> Image deleting delegate

- Lightbox.xcodeproj/project.pbxproj
#286
Removed unused `Imaginary` framework in Frameworks Folder.
> Fixed SPM resolving issue

- Source/LightboxConfig.swift
- Source/LightboxController.swift
This gives users the ability to use a custom background color using LightboxConfig.imageBackgroundColor
> Expose image background color via LightboxConfig

- Source/Library/LightboxTransition.swift
- Source/LightboxController.swift
- Source/Views/FooterView.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
- Source/Views/PageView.swift
Added `any` to each protocols to resolve `existential-any` build errors on Swift 6.  
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0335-existential-any.md
> Fix existential-any for Swift6
