hyperoslo/Lightbox

- Source/LightboxController.swift
There was a bug: if user deleted all the photos from Lightbox, it still stored an array that contained the last photo.  So, if you tried to get an edited set of photos (if all of them had been removed) - you still get one "unremovable" photo.
The problem was in improper method ordering.
> Return empty array when user deleted all the photos

- Source/LightboxController.swift
Disabling button while removing the items fixes the issue when collectionView still has been scrolling to the item which is already deleted by second tap.
> Fix crash when removing images fast

- Source/LightboxController.swift
Lightbox crashed few times because of page index being out of bounds. In rotation code colllectionView method `scrollToItemAtIndexPath` was called and caused a crash. I've constrained pageIndex to never be less than zero or greater than amount of images in LightBox.
Tested on device.
> Add page index check being out of bounds

- Source/LightboxTransition.swift
This PR make the animation time dependent on the velocity that the user applies to the swipe gesture.
We used this before in the Spotify Spots demo.
@RamonGilabert came up with this amazing math thingy. 📈
https://github.com/hyperoslo/Spots/blob/master/Examples/Spotify/Application/Controllers/PlayerController.swift#L149
> Use velocity when calculating animation time

- Source/LightboxController.swift
This PR adds an optional label to the initialiser to start the Lightbox at a specific index.
It shouldn't have any affect on the public API.
> Add startIndex to init method

- Demos/DemoLightbox/DemoLightbox/ViewController.swift
- Source/LightboxController.swift
This PR improves the rotating transition. It uses the `UIViewControllerTransitionCoordinator` in `viewWillTransitionToSize` to animate the resizing of `pageViews`.
```swift
override public func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
super.viewWillTransitionToSize(size, withTransitionCoordinator: coordinator)
coordinator.animateAlongsideTransition({ (UIViewControllerTransitionCoordinatorContext) -> Void in
self.configureLayout(size)
}, completion: nil)
}
```
It looks like this;
> Improve rotation

- Source/LightboxController.swift
- Source/Views/PageView.swift
Found a typo in the `PageViewDelegate`.
`pageVewDidZoom` -> `pageViewDidZoom`
> Fix typo in delegate method

- Source/Library/LightboxTransition.swift
Before, the dismissal delegate was not called when you swipe the image of screen, this PR fixes that issue.
> Call dismissalDelegate in finishInteractiveTransition

- .travis.yml
- Demos/DemoLightbox/DemoLightbox/Info.plist
- Demos/DemoLightbox/DemoLightbox/ViewController.swift
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxImage.swift
- Source/Views/PageView.swift
Dynamic background didn’t work with remote images. This PR fixes that issue.
Had to add another method on `PageViewDelegate` called `remoteImageDidLoad`.
This method takes an optional image and is invoked when the remote image has loaded.
`LightboxController` conforms to `PageViewDelegate` and will update the background as soon as the network request returns an image.
The demo has also been updated to allow and display a remote image.
> Fix dynamic background for remote images

- Source/LightboxController.swift
@RamonGilabert @zenangst Set `presented` to `true` only when view did appear.
> Fix presented property

- Source/Views/PageView.swift
Apparently, not using `self` here caused the application to crash when running it in release mode.
> Fix crash when compiling in release mode

- Source/LightboxImage.swift
I think these should be private. 
Consider the following use case 
```swift 
let lightBoxImage = LightboxImage(imageURL: NSURL(string: "https://cdn.arstechnica.net/2011/10/05/iphone4s_sample_apple-4e8c706-intro.jpg")!)
lightBoxImage.image  = UIImage(named: "photo1")!
lightBoxImage.addImageTo(imageView)
```
Now the implementation of `addImageTo` suggests that `imageURL` and `image` are mutually exclusive.
> Making var private

- Source/LightboxImage.swift
There maybe reason that we hide it https://github.com/hyperoslo/Lightbox/pull/72 but some people in the world want to see it, so make it `public private(set)`
> Use public private(set)

- Source/LightboxController.swift
I added a new protocol ```LightboxControllerTouchDelegate``` to inform the new delegate property ```imageTouchDelegate``` that an image was touched.
I need this new functionality to directly close the view controller. I use it like an "image picker".
> Added new protocol LightboxControllerTouchDelegate 

- Source/LightboxConfig.swift
- Source/Views/HeaderView.swift
Hey Hyper Team 👋 
I had to translate the close button to German and this happened:
With this PR, the size is based on the text with the help of `sizeToFit()`.
To not break the API for others, a size can still be set and will be used if it's not `nil`.
Have a sunny day 🌞 
Roman
> Auto-size Close and Delete buttons

- Source/LightboxController.swift
This PR fixes https://github.com/hyperoslo/Lightbox/issues/93
When the Lightbox was dismissed, the Navigation Bar (if any) was appearing at (0,0) not respecting the presence of Status Bar. It was happening because the Status Bar was turned back on too late. Making the statusBar update earlier - in viewWillDisappear - fixes this issue.
> Preserve correct Navigation Bar after dismissal when opened from a controller with a Nav Bar

- Source/LightboxController.swift
Thanks for the awesome library! I've noticed that the layout breaks on iPad in split screen mode because it relies on a call to `UIScreen.main.bounds` to perform layout calculations. I've switched to using the key window's bounds instead which fixes this problem.
> Use key window bounds instead of screen bounds

- Source/LightboxImage.swift
...continuing from PR https://github.com/hyperoslo/Lightbox/pull/115 (which was created from master by mistake).
> This change allows apps to access the images inside LightboxImage even if those images were downloaded from an external URL provided by the app.
> Can be useful, for example, when an app needs to provide sharing functionality.
> See example of such a usage in #98
> Updating the .image property of a LightboxImage instance after Lightbox has downloaded an image via URL

- Source/Views/InfoLabel.swift
This PR fixes issue https://github.com/hyperoslo/Lightbox/issues/117
A long text will be truncated quickly until it remains twice longer than numberOfVisibleLines. So that the existing character-by-character algorithm always starts with a short text.
> Cutting long texts quicker

- Source/Views/PageView.swift
This PR fixes issue https://github.com/hyperoslo/Lightbox/issues/108 and (duplicate?) issue https://github.com/hyperoslo/Lightbox/issues/116
Lightbox behaves much better on low latency network in terms of UI now - it will correctly show progress indicator while an image is being loaded (an empty slot was appearing before, and it looked as if nothing was going to happen).
> Updating the image frames while images are still being loaded

- .travis.yml
Hello!
This commit updates the continuous integration setup by selecting the
Xcode 8.3 osx_image and by indicating that the project is written in
swift.
Indeed, the continuous integration was broken, as the Carthage update
(0.24) needs this version of Xcode [1]
Thank you.
[1] https://travis-ci.org/hyperoslo/Lightbox/builds/268485681
> project: update continuous integration setup

- Source/LightboxController.swift
Hello!
This commit fixes a warning indicating that a variable value was never
mutated and should be a constant.
To fix this warning we actually replace the 'var' by a 'let'.
Thank you.
> lightboxController: fix warning

- Source/LightboxController.swift
- Source/Views/FooterView.swift
`setStatusBarHidden(_:with:)` was deprecated, causing `LightboxConfig.hideStatusBar = true` not work.
**Fix:** switched to `prefersStatusBarHidden` property to implement it.
When infoLabel's `fullText` is empty, the footer doesn't remove gradient layer properly.  
Gradient layer should be removed from footer view if infoLabel's fullText is empty, regardless of expanded state.
**Fix:** added `infoLabel.fullText.isEmpty` check in FooterView InfoLabelDelegate extension.
> Fixed two bugs.

- Lightbox.xcodeproj/project.pbxproj
- Source/Library/LightboxTransition.swift
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxImage.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
Hello!
This commit uses SwiftLint and fixes the warnings that were risen by the analysis. It uses the `.swiftlint.yml` file that was already available in the project.
Thank you!
> project: use swiftlint and fix triggered warnings

- Lightbox.podspec
Hi,
I specified version of Hue dependency in podspec to make this library compatible with Swift 3.2 projects opened in Xcode 9. See [issue 137](https://github.com/hyperoslo/Lightbox/issues/137).
Tomas
> Specified Hue dependency version in podspec - Issue 137

- Source/Views/InfoLabel.swift
I have been experiencing occasional `fatal error: cannot decrement invalid index` crashes in [line 63 ](https://github.com/hyperoslo/Lightbox/blob/master/Source/Views/InfoLabel.swift#L63) of `InfoLabel.truncatedText.getter`:
```swift
range = truncatedText.index(range.lowerBound, offsetBy: -1)..<truncatedText.index(range.upperBound, offsetBy: -1)
```
I have refactored this to use the `String.remove(at:)` collection API (re)introduced in Swift 4.
> Refactored truncatedText getter to prevent occasional EXC_BREAKPOINT crash

- Source/Views/InfoLabel.swift
String has changed in Swift 4: https://github.com/apple/swift/blob/master/docs/StringManifesto.md
Using `String.characters` is now deprecated and shows a warning when building. `String` itself is now a Collection of Characters, and can be accessed directly where we previously had to use `String.characters`. :)
> Use String directly instead of String.characters

- Source/LightboxController.swift
We can't do `configureLayout(_ size: CGSize = view.bounds.size)` because instance members can't be used as default values, so as one of the possible workarounds, I just have the caller pass in the size it wants.
Edit: This is for #150
> Use view.bounds instead of UIApplicationDelegate.window.bounds

- Source/LightboxController.swift
Bug: 
Page counter displays incorrect value for 41 images. E.g. counter is jumping from 19 to 21 on iPhone 8. 
Steps to reproduce: 
1. Open Lightbox with 41 images. 
2. Scroll back and forward. 
Expected: 
Page counter is displaying correct values. 
Actual: 
Page counter jumps from n to n+2. Last pictures are showing the same 41 counter value.  
Bug reason: you should take into account spacing while calculating current page.
> Fix footer counter

- Lightbox.xcodeproj/project.pbxproj
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxImage.swift
- Source/LightboxImageStub.swift
- Source/Views/PageView.swift
I tried to load the LightboxController with hundreds of images, and ran into memory issues.
As of now, Lightbox loads all the passed images at once, creating a memory usage spike for a high amount of images. Also it keeps all of them in memory, which is not optimal for large numbers of images. 
Therefore, it might be useful to have a possibility to set a number of images, which the user will have loaded at a time.
I implemented it in this PR. 
So if preload = 0, we load all the images (default behavior), if it equals to 2, we load:
-**2**, -**1**, **0**(current image), **1**, **2**.
> Added possibility to set image preload value

- Source/Library/Color+Extensions.swift
Using public visibility means that developers are unable to simultaneously use `Hue` along with `Lightbox` since both modules contain a globally imported extension of the same format: `UIColor.init(hex: String)`. Any project using the latest versions of both libraries will fail to compile if the hex initializer is used anywhere due to ambiguity in resolving the method.
I definitely see the reasoning behind removing the dependency on `Hue`, but the hex color extension is really only used internally to `Lightbox` and doesn't need to be publicly accessible in the module since it is wholly unrelated to the core purpose of `Lightbox`.
> Change UIColor hex extension to internal visibility

- Cartfile
- Cartfile.resolved
- Lightbox.xcodeproj/project.pbxproj
This fixes the current build error which was introduced when Imaginary updated to 4.3
> Add cache to carthage requirements.

- Package.swift
Hi,
This pull request adds a `Package.swift` file to the project, to use it in modern swift projects. I added this, because carthage isn't working any more caused by changes in Imaginary
> Introduce Swift Package Manager

- Source/LightboxController.swift
This PR fixes a little issue I got when using Lightbox with SwiftUI, when showed as a modal. What happened was that the layout is adjusted to make space for the text below the image only after the view appeared. Expected behavior since the `configureLayout(_)` was in `viewDidAppear`...
By configuring the layout inside `viewDidLayoutSubviews()`, when the view appears, it is configured with the final frame but before presentation, which makes the UI correct when it is presenting (before `viewDidAppear` is called).
> Move configureLayout(_) in viewDidLayoutSubviews()

- Lightbox.podspec
- Lightbox.xcodeproj/project.pbxproj
- Lightbox.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Lightbox.xcodeproj/xcshareddata/xcschemes/Lightbox-iOS.xcscheme
- Package.swift
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxImage.swift
- Source/Views/PageView.swift
- iOSDemo/ViewController.swift
This PR uses SDWebImage for image caching. The main reason is to support animated gif(not loading all frames into memory when playing)
> Using SDWedImage instead Imginery for caching

- Source/LightboxController.swift
- Source/Views/PageView.swift
A reliable tap event helps users hide/unhide navigation bar or toolbars to give a full unobstructed view of the image.
> Add tap delegate for tap/double tap detection

- Lightbox.podspec
- Package.swift
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/LightboxImage.swift
- Source/Views/PageView.swift
- iOSDemo/ViewController.swift
fix #284 .
Since it is undesirable to depend on a specific image library, removed `SDWebImage` dependency.  
If developers use `LightboxImage(imageURL:)`, they must also implement `LightboxConfig.loadImage` at the same time.  
The same behavior as before can be achieved by using any image library in `LightboxConfig.loadImage`.
> Remove dependencies on specific image request library

- Source/Library/LayoutConfigurable.swift
- Source/Views/FooterView.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
- Source/Library/LayoutConfigurable.swift:1:30
- Source/Views/FooterView.swift:3:37
- Source/Views/HeaderView.swift:3:30
- Source/Views/InfoLabel.swift:3:36
> fix: 'class' keyword to define a class-constrained protocol is deprecated

- Source/Library/LayoutConfigurable.swift
- Source/LightboxConfig.swift
- Source/LightboxController.swift
- Source/Views/FooterView.swift
- Source/Views/HeaderView.swift
- Source/Views/InfoLabel.swift
- Source/Views/PageView.swift
I have fixed the following build error.  
Confirmed with Xcode 16 beta 4 and Swift 6.  
`Main actor-isolated instance method '...' cannot be used to satisfy nonisolated protocol requirement`.
> Fix build error for MainActor isolation.
